### ISSUE TITLE
Good Work

### ISSUE THREAD

**Issue by RykerCohen** [abarichello/cp-swf#1]
Been looking for a good way to organize all my swf files!

**Comment by abarichello** [comment]
Hello, thanks for the compliment!
Right now It's not my intention for this to be a generic SWF viewer but i'll see what I can do. When its completed you are free to fork and change it to your needs.

**Comment by abarichello** [comment]
Hello there,
the project is finished, if you follow instructions on the README and gitlab-ci.yml you should be able to modify this project for your needs.
